{
 "title": "Requests Status and Latency",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method, status, pattern) (rate(http_requests_total{pattern!~\"GET /healthz|GET /metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95% Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method, status, pattern) (rate(http_request_duration_seconds_bucket{pattern!~\"GET /metrics|GET /healthz\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "50% Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, method, status, pattern) (rate(http_request_duration_seconds_bucket{pattern!~\"GET /healthz|GET /metrics\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Cpu Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{name!=\"global\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "aws_rds_database_connections_average{name!=\"global\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Free and Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_average{name!=\"global\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}